todo/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from todolist.views import FailedTasks

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^todolist/', include('todolist.urls')),
    url(r'^api/cron/runFailedJobs', FailedTasks.as_view()),
]

todolist/urls.py
from django.conf.urls import url

from todolist.views import HomePageView, CategoryList, CategoryCreate, CategoryDetailView, CategoryDelete, \
    CategoryUpdate, TaskCreate
from . import views

urlpatterns = [
    url(r'^$', HomePageView.as_view()),
    url(r'^categories/$', CategoryList.as_view(), name='categories'),
    url(r'^categories/create/$', CategoryCreate.as_view(), name='category-create'),
    url(r'^categories/(?P<pk>[-\w]+)/$', CategoryDetailView.as_view(), name='category-detail'),
    url(r'^categories/(?P<pk>[-\w]+)/update/$', CategoryUpdate.as_view(), name='category-update'),
    url(r'^categories/(?P<pk>[-\w]+)/delete/$', CategoryDelete.as_view(), name='category-delete'),
    url(r'^tasks/create/$', TaskCreate.as_view(), name='task-create'),

]

todolist/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone


class Category(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('category-detail', kwargs={'pk': self.pk})


class Task(models.Model):
	description = models.TextField(blank=False)
	start_date = models.DateTimeField()
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	created_at = models.DateField(default=timezone.now().strftime("%Y-%m-%d"))

	def __str__(self):
		return self.description

	def get_absolute_url(self):
		return reverse('category-detail', kwargs={'pk': self.category.id})


class FailedTask(models.Model):
	description = models.TextField(blank=False)
	failed_at = models.DateTimeField()
	category_id = models.IntegerField(blank=True)

todolist/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views import View
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from todolist.decorators import dispatch_task
from todolist.models import Category, Task, FailedTask
from todolist.tasks import adding_task
import logging
logger = logging.getLogger(__name__)


class HomePageView(View):
	def get(self, request):
		context = RequestContext(request)

		return render_to_response('todolist/index.html', {}, context)


class CategoryList(ListView):
	queryset = Category.objects.order_by('-name')


class CategoryDetailView(DetailView):
	model = Category
	template_name = 'todolist/category_detail.html'
	context_object_name = 'category'


class CategoryCreate(CreateView):
	model = Category
	fields = ('name',)
	template_name = 'todolist/category_create.html'


class CategoryUpdate(UpdateView):
	model = Category
	fields = ('name',)
	template_name = 'todolist/category_update.html'
	context_object_name = 'category'


class CategoryDelete(DeleteView):
	model = Category


class TaskCreate(CreateView):
	model = Task
	fields = ('description', 'category', 'start_date',)
	template_name = 'todolist/task_create.html'

	def post(self, request, *args, **kwargs):

		response = super(TaskCreate, self).post(self, request, *args, **kwargs)

		def run_task():
			task = adding_task.delay(1)

		dispatch_task(run_task())

		return response


class TaskUpdate(UpdateView):
	model = Task
	fields = ('description', 'category', 'start_date',)
	template_name = 'todolist/task_update.html'
	context_object_name = 'task'

	def post(self, request, *args, **kwargs):

		response = super(TaskUpdate, self).post(self, request, *args, **kwargs)

		def run_task():
			task = adding_task.delay(1)

		dispatch_task(run_task())

		return response


class FailedTasks(View):
	def get(self, request):
		tasks = FailedTask.objects.all()

		def run_task(id):
			task = adding_task.delay(id)

		for task in tasks:
			dispatch_task(run_task(task.category_id), task.category_id)

		return HttpResponse('OK')

templates/todolist/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>To Do App - {% block title %}How to Tango with Django!{% endblock %}</title>
</head>
<body>
    {% block body_block %}{% endblock %}
</body>
</html>

templates/todolist/category_create.html
{% extends 'todolist/base.html' %}

{% block title %} Add new category {% endblock %}

{% block body_block %}

<div class="card">
    <div class="card-header">
        <h5 class="card-title">Create a New Category</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Create</button>
        </form>
    </div>
</div>

{% endblock %}

templates/todolist/category_detail.html
{% extends 'todolist/base.html' %}

{% block title %} Category {% endblock %}

{% block body_block %}

<div class="card">
    <div class="card-header">
        <h5 class="card-title">Category Details #{{category.id}}</h5>
    </div>
    <div class="card-body">
        <dl class="row">
          <dt class="col-sm-3">Category Name</dt>
          <dd class="col-sm-9">{{ category.name }}</dd>
        </dl>
    </div>
    <br/>

        <div class="card-body">
            {% for task in category.task_set.all %}
                <dl class="row">
                  <dt class="col-sm-3">Task Description</dt>
                  <dd class="col-sm-9">{{ task.description }}</dd>
                  <dd class="col-sm-9">{{ task.start_date }}</dd>
                </dl>
            {% endfor %}
        </div>
</div>

{% endblock %}

templates/todolist/category_list.html
{% extends 'todolist/base.html' %}

{% block title %} Category List {% endblock %}

{% block body_block %}
    <h1>Category List</h1>
    {% if category_list %}
        <ul>
            {% for category in category_list %}
                <li><a href="/todolist/categories/{{ category.id }}">{{ category.name }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>No categories created yet!</h3>
    {% endif %}
    <br/>
    <a href="/todolist/categories/create/">Add a New Category</a>
    <br/>
    <a href="/todolist/tasks/create/">Add a New Task</a>
{% endblock %}

templates/todolist/category_update.html
{% extends 'todolist/base.html' %}

{% block title %} Add new category {% endblock %}

{% block body_block %}

<div class="card">
    <div class="card-header">
        <h5 class="card-title">Category Update: {{ category.name }}</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Update</button>
        </form>
    </div>
</div>

{% endblock %}

templates/todolist/index.html
{% extends 'todolist/base.html' %}

{% block title %}Django{% endblock %}

{% block body_block %}
    <h1>Homepage Page</h1>
    <a href="/todolist/categories/">Categories</a>
{% endblock %}

templates/todolist/task_create.html
{% extends 'todolist/base.html' %}

{% block title %} Add new task {% endblock %}

{% block body_block %}

<div class="card">
    <div class="card-header">
        <h5 class="card-title">Create a New Task</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Create</button>
        </form>
    </div>
</div>

{% endblock %}

templates/todolist/task_update.html
{% extends 'todolist/base.html' %}

{% block title %} Update task {% endblock %}

{% block body_block %}

<div class="card">
    <div class="card-header">
        <h5 class="card-title">Task Update: {{ task.name }}</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Update</button>
        </form>
    </div>
</div>

{% endblock %}